server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm
    username: root
    password: 654321
  jpa:
    hibernate:
      ddl-auto: update
    properties:
          hibernate:
            format_sql: true
            show_sql: true
